version: "27.1.1"

services:
  app:
    build:
      context: ./app
    environment:
      - FLASK_SECRET_KEY=your_secure_persistent_secret_key
    volumes:
      - ./app:/app
    restart: always
    deploy:
      replicas: 3  # Ensures there are 3 instances of the app running

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./local/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    restart: always
