version: "4"

services:
  app:
    build:
      context: app
    ports:
      - "5000"
    environment:
      - ENV_VAR=cherry
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
    environment:
      - ENV_VAR=nginx