services:
    app:
        build:
            context: ./app
        ports:
            - "5000"
        deploy:
            replicas: 3
    
    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        profiles: ["nginx-normal"]
           
    nginx-certbot:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        profiles: ["nginx-certbot"]
        
    nginx-load-balancing:
        container_name: nginx-lb
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/loadbalanced-nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        profiles: ["nginx-lb"]
            
    certbot:
        image: certbot/certbot
        container_name: cb
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email root@999root.xyz -d www.999root-search.online --agree-tos